import React from 'react';
import CustomParallax from "../components/CustomParallax";
import menu_top from "../assets/menu_top.jpg";
import Container from "@material-ui/core/Container";

export default function Terms() {
    return (
        <div>
            <CustomParallax title='Terms of Service' img={menu_top} height={300}/>
            <Container>
                <div className="cell-wrapper layout-widget-wrapper">
                    <span id="hs_cos_wrapper_left_column" className="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text" style={{}}
                          data-hs-cos-general-type="widget" data-hs-cos-type="rich_text">
                    <h3 className='text-center' style={{textAlign: 'left', fontWeight: 'normal', fontFamily: 'Roboto'}}>TERMS OF USE</h3>
                    <h3 className='text-center' style={{textAlign: 'left', fontWeight: 'normal', fontFamily: 'Roboto'}}>INDEPENDENT CONTRACTOR SERVICES AGREEMENT</h3>
                    <p className='text-center' style={{textAlign: 'left'}}>Updated: August 7, 2019<br/>
                    Sections: 2.1</p>
                    <p style={{textAlign: 'left'}}>The Mama's Restaurant Mobile Application is an internet application (“Mama's Restaurant Mobile Application” or the “Application”) owned and operated by Mama's Restaurant (“Mama's Restaurant,” “we,” or “us”). Mama's Restaurant provides a service (the “Service”) that allows its customers (“Customers”) to access Mama's Restaurant’s network of contractors (“Mama's Restauranters” or “you” or “Contractor”) to identify local providers to meet intermittent needs for services. The Mama's Restauranters have access to the Application to receive and review requests for services from Customers and to determine their interest in and availability to respond to such requests.</p>
                    <p style={{textAlign: 'left'}}><strong>PLEASE READ THIS AGREEMENT CAREFULLY. THIS AGREEMENT CONTAINS A MANDATORY INDIVIDUAL ARBITRATION AND CLASS ACTION WAIVER PROVISION THAT REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE COVERED DISPUTES, RATHER THAN JUDGE OR JURY TRIALS.</strong></p>
                    <p style={{textAlign: 'left'}}><strong>Acknowledgment and Acceptance of Independent Contractor Services Agreement</strong></p>
                    <p style={{textAlign: 'left'}}>This Terms of Use Independent Contractor Services Agreement (“Terms of Use” or “Agreement”) is an electronic contract that sets out the legally binding terms of the relationship between Mama's Restaurant and you. By registering to become a Mama's Restauranter, you accept and agree to be bound by the terms of this Agreement. Please read it carefully. By accessing the Application, or becoming a Mama's Restauranter, you accept this Agreement and agree to the terms, conditions and notices contained and/or referenced herein.</p>
                    <p style={{textAlign: 'left'}}>Mama's Restaurant reserves the right to change this Agreement, and add additional terms at any time, effective upon making the modified provisions available on the Application or by notifying Mama's Restauranters directly. You are responsible for regularly reviewing the Terms of Use for modifications and updates to its terms. Continued use of the Application after any such changes are made to this Agreement shall constitute your consent to such changes. Other than making the changes available on the Application, Mama's Restaurant does not assume any obligation to notify Mama's Restauranters of any changes to this Agreement, or the creation or modification of any additional terms.</p>
                    <p style={{textAlign: 'left'}}><strong>Notwithstanding the previous paragraph or any contrary language in this Agreement, the Arbitration Agreement in Section 9 of this Agreement may not be modified or terminated absent a writing signed (electronically or otherwise) by the Company and You.</strong></p>
                    <p style={{textAlign: 'left'}}>You acknowledge that you are able to electronically receive, download, and print this Agreement, any other terms, notices, forms (including IRS Form 1099-MISC) and any other notices or documents required by, or incorporated into, this Agreement by reference, any amendments to this Agreement, or any other items required by regulation or law. Further, you agree to keep the contact information in your Account current at all times including, but not limited to, your email address, physical address, and phone number.</p>
                    <p style={{textAlign: 'left'}}>Use of the Application is permitted only by individuals who can form legally binding contracts under applicable law. Without limiting the foregoing, you must be at least 18 years old [or the age of legal majority in the jurisdiction in which you work] and legally authorized to work in the United States to become a Mama's Restauranter. If you do not meet these criteria, you may not register to become a Mama's Restauranter.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>1. &nbsp;DEFINITIONS</h3>
                    <p style={{textAlign: 'left'}}>Capitalized terms are defined as set forth below or elsewhere in the Agreement.</p>
                    <p style={{textAlign: 'left'}}><strong>1.1</strong>&nbsp;&nbsp;<strong>“Services”</strong>&nbsp;means the services described in a Mama's Restaurant Request for services by a Mama's Restauranter to a Mama's Restaurant Customer.</p>
                    <p style={{textAlign: 'left'}}><strong>1.2</strong>&nbsp;&nbsp;<strong>“Mama's Restaurant Request</strong>” means a notice provided, through the Application, to one or more Mama's Restauranters, which includes a description of the services to be provided by the Mama's Restauranters, the time by which the Mama's Restaurant Request must be completed (the “Mama's Restaurant Completion Date”) and the fee associated with the Mama's Restaurant Request (the “Payment”). An open request is a request for services that has not yet been accepted by a Mama's Restauranter (“Open Request”). Mama's Restauranters can use the Application to review Open Requests and to indicate their availability for Open Requests. Once a Mama's Restauranter has accepted a Mama's Restaurant Request pursuant to Section 2, the Mama's Restaurant Request will become a “Mama's Restaurant Engagement”. Each Mama's Restaurant Engagement constitutes a new contract between Mama's Restaurant and the Mama's Restauranter, and between the Mama's Restauranter and Requestor.</p>
                    <p style={{textAlign: 'left'}}><strong>1.3</strong>&nbsp;&nbsp;“<strong>Mama's Restaurant Mobile Application</strong>” or <strong>“Application” </strong>means the software application used by Mama's Restaurant in connection with the Services.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>2. &nbsp;Mama's RestaurantERS</strong></h3>
                    <p style={{textAlign: 'left'}}><strong>2.1 </strong><strong>Customer Conditional Offer Requirements and Privacy Information.</strong>&nbsp; Some customers may require completion of certain steps or requirements after you accept a Mama's Restaurant Request before you perform the Mama's Restaurant Request (“Conditional Offer Requirements”).&nbsp; Any Conditional Offer Requirements will be explained after you accept the Mama's Restaurant Request.&nbsp; Failure to complete such Conditional Offer Requirements to the satisfaction of the Customer will result in your inability to perform accepted Mama's Restaurant Requests.&nbsp; Please note that some of the Conditional Offer Requirements will require Mama's Restaurant or a designated third-party provider to ask for your social security number and share it with entities who require the information to facilitate the Conditional Offer Requirements.&nbsp; Mama's Restaurant may also share your social security number with our payment vendor, Stripe, in order to verify your payment account to ensure the safety of your account.</p>
                    <p style={{textAlign: 'left'}}><strong>2.2 Best Efforts.</strong> By registering to become a Mama's Restauranter and accepting an Open Request, you agree to use your best efforts to perform the Mama's Restaurant Engagement such that the Services meet the requirements and specifications of the Customer, for whom the Open Request was created. Once a Mama's Restauranter has accepted a Mama's Restaurant Request, the Open Request will no longer be available for performance by other Mama's Restauranters who received the Open Request. By accepting an Open Request, you are entering into a binding legal agreement to provide the Services for the Payment specified in the Open Request. Do not accept an Open Request unless you are sure that:&nbsp; (1) you understand what you are being asked to deliver; (2) you can perform the Services identified in the Open Request; (3) you can deliver the Services in the requested time period; and if required, you can get to and from the Customer’s location. Failure to timely deliver the Services consistent with the Customer’s requirements and specifications will constitute a breach, resulting in non-payment. Further, in the event of such a breach, you will be responsible for payment of any additional fees (e.g., rush fees) or costs incurred as a result of your failure to timely complete the Open Request in accordance with the Customer requirements. You agree to not possess, sell, receive, or operate under the influence of any drugs or alcohol while performing any Mama's Restaurant Engagement.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>3. &nbsp;INDEPENDENT CONTRACTOR RELATIONSHIP</strong></h3>
                    <p style={{textAlign: 'left'}}>Nothing in this Agreement is intended or should be construed to create a partnership, joint venture, or employer-employee relationship between Mama's Restaurant and you or between the Customer and you. You will take no position with respect to or on any tax return or application for benefits, or in any proceeding directly or indirectly involving Mama's Restaurant that is inconsistent with your being an independent contractor (and not an employee) of Mama's Restaurant. You are not the agent of Mama's Restaurant or the Customer and you are not authorized, and must not represent to any third party that you are authorized, to make any commitment or otherwise act on behalf of Mama's Restaurant or the Customer.</p>
                    <p style={{textAlign: 'left'}}>As an independent contractor, you are solely responsible for determining which Open Requests you will choose to accept and how, when and where you will provide the Services under this Agreement.</p>
                    <p>Mama's Restaurant does not restrict the Mama's Restauranter’s right to provide services through other parties, including competitors of the Mama's Restaurant Mobile Application; Mama's Restaurant expects the individual performing services as a Mama's Restauranter will provide services for other parties;</p>
                    <p>Mama's Restauranter acknowledges and represents Mama's Restauranter can earn income from other sources; Mama's Restaurant does not guarantee the Mama's Restauranter any minimum amount of Mama's Restaurant Engagements;</p>
                    <p>Mama's Restaurant does not provide a performance assessment for Mama's Restauranters, and does not oversee the actual work or instruct the individual as to how the work will be performed, or the method or process the Mama's Restauranter uses to perform services;</p>
                    <p>Mama's Restaurant does not pay a salary or hourly rate but rather facilitates Requestor’s payment of the rate set by the Requestor;</p>
                    <p>Mama's Restaurant does not terminate the work during the term of this Agreement unless the Mama's Restauranter violates the terms of this Agreement or fails to produce a result that meets the specifications of the Agreement;</p>
                    <p>Mama's Restaurant does not provide training, tools, equipment, benefits, or expense reimbursement to the Mama's Restauranter;</p>
                    <p>Mama's Restaurant does not dictate the time of performance;</p>
                    <p>Mama's Restaurant does not combine its business operations in any way with the Mama's Restauranter’s business, but instead maintains such operations as separate and distinct. Mama's Restauranter shall have no legal authority to enter into contracts on Mama's Restaurant’s behalf or otherwise bind Mama's Restaurant in any way.</p>
                    <p>Mama's Restauranter is responsible for obtaining and maintaining any required registration, licenses, or other authorization necessary for the services Mama's Restauranter renders.</p>
                    <p>For purposes of New York City Local Law 140 only, to the extent it is deemed to apply, the “value” of the services performed pursuant to this Agreement is equal to the total amount paid by the Requestor for each service.</p>
                    <p style={{textAlign: 'left'}}>Without limiting the generality of the foregoing:</p>
                    <p style={{textAlign: 'left'}}><strong>3.1</strong>&nbsp;&nbsp;<strong>Benefits and Contributions.</strong>&nbsp;You are not entitled to or eligible for any benefits that Mama's Restaurant, its parents, subsidiaries, affiliates or other related entities may make available to its employees, such as group insurance, profit-sharing or retirement benefits. Because you are an independent contractor, Mama's Restaurant will not withhold or make payments for social security, make unemployment insurance or disability insurance contributions, or obtain workers’ compensation insurance on your behalf. If, notwithstanding the foregoing, you are reclassified as an employee of Mama's Restaurant, or any affiliate of Mama's Restaurant (“Affiliate”), by the U.S. Internal Revenue Service (“IRS”), the U.S. Department of Labor (“DOL”), or any other federal, state or foreign court or agency, you agree that you will not, as the result of such reclassification, be entitled to or eligible for, on either a prospective or retrospective basis, any employee benefits under any plans or programs established or maintained by either the Customer and its parents, subsidiaries, affiliates or related entities or by Mama's Restaurant, its parents, subsidiaries, affiliates or other related entities.</p>
                    <p style={{textAlign: 'left'}}><strong>3.2</strong>&nbsp;&nbsp;<strong>Taxes.</strong> You are solely responsible for filing all tax returns and submitting all payments as required by any federal, state, local, or foreign tax authority arising from the payment of Payments to you under this Agreement, and you agree to do so in a timely manner. You will comply with all applicable federal, state, local, and foreign laws governing self-employed individuals, including laws requiring the payment of taxes, such as income and employment taxes, and social security, disability and other contributions. To the extent required by the IRS, Mama's Restaurant will report the Payments paid to you for services rendered as part of Mama's Restaurant engagements by filing Form 1099-MISC with IRS. You consent to electronic delivery of Form 1099-MISC, if such form is required or filed. You agree to indemnify Mama's Restaurant for the cost of any tax liabilities incurred by Mama's Restaurant as a result of your failure to pay all applicable taxes in a timely manner.</p>
                    <p style={{textAlign: 'left'}}><strong>3.3 &nbsp;Third Party Payment Processing Services.</strong>&nbsp;Payment processing services for Mama's Restauranters are provided by Stripe and are subject to the&nbsp;
                        <a href="https://stripe.com/connect-account/legal">Stripe Connected Account Agreement</a>, which includes the&nbsp;<a
                            href="https://stripe.com/US/legal">Stripe Terms of Service</a> (collectively, the “Stripe Services Agreement”). These documents can be found at the provided links or by using a search engine (such as Google or Bing) to seek the terms “Stripe Connected Account Agreement” or “Stripe Terms of Service,” respectively.” By agreeing to these terms or continuing to operate as a Mama's Restauranter on Mama's Restauranter, you agree to be bound by the Stripe Services Agreement, as the same may be modified by Stripe from time to time. As a condition of Mama's Restaurant enabling payment processing services through Stripe, you agree to provide Mama's Restaurant accurate and complete information about you and your business, and you authorize Mama's Restaurant to share it and transaction information related to your use of the payment processing services provided by Stripe.</p>
                    <p style={{textAlign: 'left'}}><strong>3.4&nbsp; On-Demand Independent Contractors Association Membership Enrollment.</strong> By agreeing to this Membership Enrollment Application, I understand I am agreeing to enroll in the On-Demand Independent Contractors Association (ODICA) and I am also agreeing to abide by the Bylaws of ODICA, as amended from time to time.</p>
                    <p style={{textAlign: 'left'}}>Membership in ODICA is non-transferable and only one membership in ODICA is allowed per eligible person. A member may cancel his or her membership within thirty (30) days from the date you join ODICA, by sending a cancellation letter with your name and membership number to Member Services. ODICA bylaws are available upon request. Nothing herein creates the relationship of employer-employee between member and ODICA. Members of ODICA have access to certain benefits and/or products offered by ODICA, or sponsored by ODICA, Benefits and/or products are offered at the sole discretion of ODICA, and may vary by availability, vendor or the member’s state of residence. ODICA may change vendors or immediately terminate the benefits and/or products offered without prior notice to members. Termination of membership in ODICA will result in the loss of such benefits and/or products. By signing this form you authorize ODICA to share your information with such third-party vendors on an as needed basis only.</p>
                    <p style={{textAlign: 'left'}}>Non-Voting Membership: By signing this form, I understand that I am enrolling as a non-dues-paying member of ODICA with no voting rights. I hereby state that I certify to the best of my knowledge and belief that all information on this form is complete and truthful and I am 18 years of age or older. Membership in ODICA is effective the first day of the month in which the member enrolls.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>4. &nbsp;CONFIDENTIALITY</strong></h3>
                    <p style={{textAlign: 'left'}}><strong>4.1&nbsp;&nbsp;Use and Disclosure.</strong>&nbsp;From time to time, you may be given access to confidential information in the course of performing engagements that you receive through Mama's Restaurant. During the term of this Agreement and at all times thereafter, you will (a) hold all Confidential Information in strict trust and confidence, (b) refrain from using or permitting others to use Confidential Information in any manner or for any purpose not expressly permitted or required by this Agreement, and (c) refrain from disclosing or permitting others to disclose any Confidential Information to any third party without obtaining Mama's Restaurant’s express prior written consent on a case-by-case basis. “Confidential Information” means any and all information related to Mama's Restaurant’s or any Customer’s business (including trade secrets, technical information, business forecasts and strategies, marketing plans, customer and supplier lists, personnel information, financial data, and proprietary information of third parties including Customers) that Mama's Restaurant and/or the Customer considers to be confidential or proprietary or which Mama's Restaurant has a duty to treat as confidential.</p>
                    <p style={{textAlign: 'left'}}><strong>4.2&nbsp;&nbsp;Standard of Care.</strong> You will protect the Confidential Information from unauthorized use, access, or disclosure in the same manner as you protect your own confidential or proprietary information of a similar nature, and with no less than reasonable care. You <span
                        style={{fontWeight: 400}}>agree that you will comply with the terms of the Mama's Restaurant <a
                        href="https://www.Mama's Restaurant.com/acceptable-use-policy/">Acceptable Use Policy</a> with respect to your use of the Service (including the Mama's Restaurant Platform) which can be found at</span>www.Mama's Restaurant.com/acceptable-use-policy/ . Further, you <span
                        style={{fontWeight: 400}}>agree that you will comply with the terms of the Mama's Restaurant <a
                        href="https://www.Mama's Restaurant.com/privacy/">Privacy Policy</a> with respect to your use of the Service (including the Mama's Restaurant Platform) which can be found at</span> www.Mama's Restaurant.com/privacy/ .</p>
                    <p style={{textAlign: 'left'}}><strong>4.3&nbsp;&nbsp;Exceptions.</strong>&nbsp;Your obligations under Sections 4.1 and 4.2 will terminate with respect to any particular information that you can prove, by clear and convincing evidence, (a) you lawfully knew prior to Mama's Restaurant’s first disclosure to you, (b) a third party rightfully disclosed to you free of any confidentiality duties or obligations, or (c) is, or through no fault of you has become, generally available to the public. Additionally, you will be permitted to disclose Confidential Information to the extent that such disclosure is expressly approved in writing by Mama's Restaurant, or is required by law or court order, provided that you immediately notify Mama's Restaurant in writing of such required disclosure and cooperate with Mama's Restaurant, at Mama's Restaurant’s reasonable request and expense, in any lawful action to contest or limit the scope of such required disclosure, including filing motions and otherwise making appearances before a court.</p>
                    <p style={{textAlign: 'left'}}><strong>4.4&nbsp;&nbsp;Removal; Return.</strong>&nbsp;Upon Mama's Restaurant’s request and upon any termination or expiration of this Agreement, you will promptly (a) return to Mama's Restaurant or, if so directed by Mama's Restaurant, destroy all Confidential Information (in every form and medium), (b) permanently erase all electronic files containing or summarizing any Confidential Information, and (c) certify to Mama's Restaurant in writing that you have fully complied with these obligations.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>5. &nbsp;NO CONFLICTS</strong></h3>
                    <p style={{textAlign: 'left'}}>You represent and warrant that you are not subject to any contract or duty that would be breached by entering into or performing your obligations under this Agreement, or any Mama's Restaurant Engagement, or that is otherwise inconsistent with this Agreement or any Mama's Restaurant Engagement.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>6. &nbsp;REPRESENTATIONS AND WARRANTIES</strong></h3>
                    <p style={{textAlign: 'left'}}><strong>6.1&nbsp;&nbsp;General.&nbsp;</strong>You represent, warrant, and covenant that:</p>
                    <p style={{textAlign: 'left'}}>(a)&nbsp;&nbsp;You have full right, power, and authority to enter into and perform under this Agreement without the consent of any third party (including any of your current or former employers);</p>
                    <p style={{textAlign: 'left'}}>(b)&nbsp;&nbsp;You will comply with all of the terms of this Agreement;</p>
                    <p style={{textAlign: 'left'}}>(c)&nbsp; You will fully conform to the Customer specifications, requirements, and other terms of any Mama's Restaurant Request that you accept, and the Services delivered will be of a professional and workmanlike quality;</p>
                    <p style={{textAlign: 'left'}}>(d) You will comply with all applicable laws, rules and regulations in connection with performance of the Services under this Agreement;</p>
                    <p style={{textAlign: 'left'}}>(e) Any workers that you may employ, engage or otherwise retain to assist with performance of Services under this Agreement are properly classified and treated under any applicable laws and will assist with the performance of Services in a safe, lawful and workmanlike manner.</p>
                    <p>(f) You are not providing and will not provide labor or services to Mama's Restaurant for remuneration, but rather, you can use the Application to find and, if you wish, accept Mama's Restaurant Requests posted by <span
                        className="gmail_default">Customers</span>.</p>
                    <p>(g) You will at all points remain free from the control and direction of Mama's Restaurant in connection with your use of the Application and the Service, including during your consideration and acceptance of any Mama's Restaurant Requests and during the performance of any Mama's Restaurant Engagements.</p>
                    <p>(h) You recognize that Mama's Restaurant is an on-demand software-driven staffing platform and agree that Mama's Restaurant Requests posted by Customers are for work that is outside the usual course of Mama's Restaurant’s business.</p>
                    <p style={{textAlign: 'left'}}><strong>6.2.&nbsp;&nbsp;Indemnification. </strong>You will indemnify and hold harmless Mama's Restaurant and its parents, affiliates, employees, and agents from and against any and all liabilities, losses, damages, costs, and other expenses (including attorney fees and costs associated with litigation) arising from or relating to a breach by you of any representation, warranty, covenant, or obligation in this Agreement, or arising from or relating to any negligent or intentional act or omission committed by you, in connection with the performance of any Mama's Restaurant engagement, which act or omission gives rise to any claim for damages against you, Mama's Restaurant and/or its parents, affiliates, employees or agents. Mama's Restaurant specifically denies any obligation to defend and/or indemnify you from and against any third party claims made against you arising from any negligent or intentional act or omission committed by you in connection with the performance of any Mama's Restaurant engagement.</p>
                    <p style={{textAlign: 'left'}}><strong>6.3&nbsp;&nbsp;Insurance.&nbsp;</strong>You acknowledge that you are an independent contractor, not an employee of Mama's Restaurant. As such, you acknowledge and understand that you are not covered by any insurance that may be provided by Mama's Restaurant to its employees, including, without limitation, health insurance, workers compensation insurance, general liability insurance, and automobile liability insurance. Mama's Restaurant requires that, as an independent contractor, you maintain workers’ compensation or occupational accident insurance for which you are solely and exclusively responsible for. Specifically, in the event that you are injured while working in the course and scope of an engagement for Mama's Restaurant, you acknowledge and understand that you will not be covered by any workers compensation insurance coverage that Mama's Restaurant may provide to its employees. Further, in the event that your actions cause an injury to a third party while you are working in the course and scope of performing a Mama's Restaurant Engagement or the Services, you acknowledge and understand that you will not be covered by any general liability or automobile liability insurance coverage that Mama's Restaurant may have, and that Mama's Restaurant is not making any commitment to defend and/or indemnify you in such circumstances, and specifically denies such obligation. <strong>If you do not provide proof of workers’ compensation or occupational accident insurance, you will be charged a Trust and Safety Fee that will be paid towards Mama's Restaurant’s supplemental occupational accident insurance.</strong> By agreeing to these Terms, you are agreeing to pay this fee.</p>
                    <p style={{textAlign: 'left'}}><strong>6.4&nbsp;&nbsp;Warranty Disclaimer.</strong> The Application is provided “as is,” as available and without any warranties or conditions (express or implied, including the implied warranties of merchantability, accuracy, fitness for a particular purpose, title and non-infringement, arising by statute or otherwise in law or from a course of dealing or usage or trade). We disclaim all and make no representations or warranties, of any kind, either express or implied, as to the quality, identity or reliability of any third party, or as to the accuracy of the postings made on the Application by any third party. Some states and jurisdictions do not allow for all the foregoing limitations on implied warranties, so to that extent, if any, some or all of the above limitations may not apply to you.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>7. &nbsp;LIMITATION OF LIABILITY</strong></h3>
                    <p style={{textAlign: 'left'}}>IN NO EVENT WILL Mama's Restaurant BE LIABLE FOR ANY CONSEQUENTIAL, INDIRECT, EXEMPLARY, SPECIAL, INCIDENTAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THIS AGREEMENT, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF BUSINESS OPPORTUNITIES OR LOSS OF GOODWILL, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. Mama's Restaurant’S TOTAL CUMULATIVE LIABILITY IN CONNECTION WITH THIS AGREEMENT, WHETHER IN CONTRACT OR TORT OR OTHERWISE, WILL NOT EXCEED THE AGGREGATE AMOUNT OF PAYMENTS OWED BY Mama's Restaurant FOR Mama's Restaurant ENGAGEMENTS PERFORMED UNDER THIS AGREEMENT DURING THE TWELVE-MONTH PERIOD PRIOR TO THE OCCURRENCE OF THE FIRST CLAIM TO GIVE RISE TO LIABILITY UNDER THIS AGREEMENT.</p>
                    <p style={{textAlign: 'left'}}>SOME STATES AND JURISDICTIONS DO NOT ALLOW FOR ALL OF THE FOREGOING EXCLUSIONS AND LIMITATIONS OF CERTAIN TYPES OF DAMAGES, SO TO THAT EXTENT, IF ANY, SOME OR ALL OF THESE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>8. &nbsp;TERM &amp; TERMINATION</strong></h3>
                    <p style={{textAlign: 'left'}}><strong>8.1&nbsp; Term; Termination by Mama's Restaurant. </strong>This Agreement is for a term of 60 days, and is automatically and continuously renewed for additional 60-day terms with continued use. In the event more than 60 days passes without the Mama's Restauranter using the Mama's Restaurant Mobile Application, then the Mama's Restauranter’s next use constitutes a renewal of this Agreement. Mama's Restaurant reserves the right to terminate your access to the Application if you have not accepted a Mama's Restaurant Engagement in the previous twelve calendar months, if you materially breach the Agreement or any Mama's Restaurant Engagement, if you violate the law in connection with your use of the Application (or in connection with the performance of the Services) or if you have otherwise engage in conduct in using the Application that Mama's Restaurant, in its sole discretion, believes in good faith to be detrimental to its business interests.</p>
                    <p style={{textAlign: 'left'}}><strong>8.2&nbsp;&nbsp;Survival. </strong>Sections 3 (“Independent Contractor Relationship”), 4 (“Confidentiality”), 5 (“No Conflicts”), 6 (“Representations and Warranties”), 7 (“Limitation of Liability”), 8.2 (“Survival”), and 9 (“General Provisions”) will survive any termination or expiration of this Agreement and/or any modification or termination of the Application. Termination or expiration of this Agreement will not affect either party’s liability for any breach of this Agreement such party may have committed before such expiration or termination.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>9. &nbsp;GENERAL PROVISIONS</strong></h3>
                    <p style={{textAlign: 'left'}}><strong>9.1&nbsp;&nbsp;Law.&nbsp;Except for the “Mandatory Binding Individual Arbitration And Class Action Waiver” below, which is governed by the Federal Arbitration Act,</strong> this Agreement or any claim, cause of action or dispute (“Claim”) arising out of or related to this Agreement shall be governed by the laws of the state of in which the Mama's Restauranter resides regardless of your country of origin or where you access Mama's Restaurant, and notwithstanding any conflicts of law principles.</p>
                    <p style={{textAlign: 'left'}}><strong>9.2&nbsp;&nbsp;&nbsp;</strong><strong>Mandatory Binding Individual Arbitration and Class Action Waiver</strong> (“Arbitration Agreement”). The Company and Contractor mutually agree to resolve any justiciable disputes between them exclusively through final and binding arbitration instead of filing a lawsuit in court. This Arbitration Agreement is governed by the Federal Arbitration Act (9 U.S.C. §§ 1-16) and, except as otherwise provided in this Arbitration Agreement, shall apply to any and all claims arising out of or relating to this Contract, the Contractor’s classification as an independent contractor, Contractor’s provision of services to the Company or its Customers, the payments received by Contractor for providing services to the Company or its Customers, the termination of this Contract, and all other aspects of the Contractor’s relationship with the Company, past, present or future, whether arising under federal, state or local statutory and/or common law, including without limitation harassment, discrimination or retaliation claims and claims arising under or related to the Civil Rights Act of 1964, Americans With Disabilities Act, Age Discrimination in Employment Act, Family Medical Leave Act, or Fair Labor Standards Act, state statutes or regulations addressing the same or similar subject matters, claims based on a joint employment or misclassification theory, and all other federal or state legal claims arising out of or relating to Contractor’s relationship or the termination of that relationship with the Company. The agreement by Contractor and the Company to mutually arbitrate disputes provides consideration for this Arbitration Agreement. This Arbitration Agreement applies to claims and disputes that the Company may have against Contractor and/or that Contractor may have against the Company, and (1) its affiliates and partners (2) its officers, directors, employees, or agents in their capacity as such or otherwise, and/or (3) all successors and assigns of any of them; any and all of which may enforce this Arbitration Agreement.</p>
                    <p style={{textAlign: 'left'}}>To the fullest extent permitted by law, the Arbitrator, and not any federal, state, or local court or agency, shall have exclusive authority to resolve any dispute relating to the formation, interpretation, applicability, enforceability or alleged waiver of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable.</p>
                    <p style={{textAlign: 'left'}}>This Arbitration Agreement does not apply to any claim that may not be arbitrated as provided by governing law. This Arbitration Agreement also does not apply to Private Attorney General Action claims under California law, which may only be brought in a court of law—not in arbitration.</p>
                    <p style={{textAlign: 'left'}}>(a)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;If either party wishes to initiate arbitration, the initiating party must notify the other party in writing via certified mail, return receipt requested, or hand delivery within the applicable statute of limitations period. This demand for arbitration must include (1) the name and address of the party seeking arbitration, (2) a statement of the legal and factual basis of the claim, and (3) a description of the remedy sought. Any demand for arbitration by Contractor may be delivered to Mama's Restaurant at <a
                        href="mailto:legal@Mama's Restaurant.com">legal@Mama's Restaurant.com</a> so long as the details set forth in the previous sentence are presented in the demand for arbitration.</p>
                    <p style={{textAlign: 'left'}}>(b)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;<strong>Class Action Waiver.</strong> <strong>The Company and Contractor mutually agree that by entering into this Arbitration Agreement, both waive their right to have any dispute or claim brought, heard or arbitrated as a class action and/or collective action, and an arbitrator shall not have any authority to hear or arbitrate any class and/or collective action (“Class Action Waiver”). In any case in which (1) the dispute is filed as a class and/or collective action and (2) there is a final determination that all or part of the Class Action Waiver is unenforceable, the class or collective action to that extent must be litigated in a civil court of competent jurisdiction (if at all), but the portion of the Class Action Waiver that is enforceable shall be enforced in arbitration.</strong></p>
                    <p style={{textAlign: 'left'}}>(c)&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Contractor agrees and acknowledges that entering into this Arbitration Agreement does not change Contractor’s status as an independent contractor in fact and in law, that Contractor is not an employee of the Company or the Company’s Customer and that any disputes in this regard shall be subject to arbitration as provided in this Arbitration Agreement.</p>
                    <p style={{textAlign: 'left'}}>(d)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;Any arbitration shall be governed by the American Arbitration Association Commercial Arbitration Rules (“AAA Rules”), although the parties may stipulate that the arbitration shall be governed by the American Arbitration Association Employment Arbitration Rules, depending on the claims at issue. In addition to and to the extent inconsistent with the foregoing AAA Rules, the following rules shall apply to any arbitration conducted pursuant to this Arbitration Agreement, unless the parties stipulate otherwise:</p>
                    <p style={{textAlign: 'left'}}>(1)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;The arbitration shall be heard by one arbitrator selected in accordance with the AAA Rules. The arbitrator shall be a licensed attorney or retired judge with experience in the law underlying the dispute.</p>
                    <p style={{textAlign: 'left'}}>(2)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;If the parties cannot otherwise agree on a location for the arbitration, the arbitration shall take place in the county in which Contractor performed his contractual duties for The Company.</p>
                    <p style={{textAlign: 'left'}}>(3)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;Unless applicable law provides otherwise, as determined by the Arbitrator, the parties agree that the Company shall pay all of the Arbitrator’s fees and costs; however, if Contractor initiates arbitration, then Contractor must bear the extent of such costs (if any) as Contractor would be required to bear in bringing and maintaining a comparable legal proceeding outside of arbitration.</p>
                    <p style={{textAlign: 'left'}}>(4)&nbsp; &nbsp; &nbsp; The Arbitrator shall be empowered to order such discovery, by way of deposition, interrogatory, document production, or otherwise, as the arbitrator considers necessary to a full and fair exploration of the issues in dispute, taking into consideration that arbitration is designed to be a speedy and efficient method for resolving disputes.</p>
                    <p style={{textAlign: 'left'}}>(5)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;Except as provided in the Class Action Waiver, the Arbitrator may award all remedies to which a party is entitled under applicable law and which would otherwise be available in a court of law, but shall not be empowered to award any remedies that would not have been available in a court of law for the claims presented in arbitration. The Arbitrator shall apply the state or federal substantive law, or both, as is applicable.</p>
                    <p style={{textAlign: 'left'}}>(6)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;The Arbitrator may hear motions to dismiss and/or motions for summary judgment and will apply the standards of the Federal Rules of Civil Procedure governing such motions.</p>
                    <p style={{textAlign: 'left'}}>(7)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;The Arbitrator’s decision or award shall be in writing with findings of fact and conclusions of law. The award issued by the Arbitrator may be entered in any court of competent jurisdiction.</p>
                    <p style={{textAlign: 'left'}}>(8) &nbsp; &nbsp; &nbsp; &nbsp;Either the Company or Contractor may apply to a court of competent jurisdiction for temporary or preliminary injunctive relief on the ground that without such relief the arbitration provided in this paragraph may be rendered ineffectual; provided, however, that all determinations of final relief shall be decided in arbitration, and pursuing the temporary or preliminary injunctive relief shall not constitute a waiver of rights under this agreement to arbitrate.</p>
                    <p style={{textAlign: 'left'}}>(e)&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;Regardless of any other terms of this arbitration agreement, claims may be brought before and remedies awarded by an administrative agency (such as the National Labor Relations Board, Occupational Safety and Health Administration, Equal Employment Opportunity Commission, the U.S. Department of Labor, or similar state or local administrative agencies) if applicable law permits access to such an agency notwithstanding the existence of an agreement to arbitrate governed by the Federal Arbitration Act.</p>
                    <p style={{textAlign: 'left'}}>(f) &nbsp; &nbsp; &nbsp;&nbsp; The AAA Rules may be found at <a
                        href="https://www.adr.org/Rules">https://www.adr.org/Rules</a> or by searching for “AAA Commercial Arbitration Rules” (or if applicable, “AAA Employment Arbitration Rules”) using a service such as www.Google.com or www.Bing.com or by asking <a
                        href="mailto:legal@Mama's Restaurant.com">legal@Mama's Restaurant.com</a>&nbsp;to provide a copy.</p>
                    <p style={{textAlign: 'left'}}>(g) &nbsp; &nbsp; &nbsp; This arbitration agreement is the full and complete agreement relating to the formal resolution of disputes covered by this arbitration agreement. In the event any portion of this arbitration agreement is deemed unenforceable, the remainder of this arbitration agreement will be enforceable. Therefore, terms of this Arbitration Agreement shall be severed, to the smallest extent possible, if required to uphold the enforceability of this Arbitration Agreement. The Arbitration Agreement is a contractual agreement to mutually arbitrate claims; therefore any statements in any Company handbooks or policies that otherwise disclaim contracts do not apply to this Arbitration Agreement.</p>
                    <p style={{textAlign: 'left'}}><strong>9.3 &nbsp;Modifications to Application.&nbsp;</strong>Mama's Restaurant reserves the right at any time to modify or discontinue, temporarily or permanently, the Application or the Service (or any part thereof) with or without notice. However, as stated above in Section 8.2 above, Section 9 (“General Provisions”), which contains the Arbitration Agreement, will survive any termination or expiration of this Agreement and/or any modification or termination of the Application or the Service. You agree that Mama's Restaurant shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Application or the Services.</p>
                    <h3 style={{fontFamily: 'Roboto'}}>10. Responding to Legal Process</h3>
                    <p>Stripe may respond to and comply with any writ of attachment, lien, levy, subpoena, warrant, or other legal order (“Legal Process”) that we believe to be valid. We or any Payment Method Provider (including, where applicable, the Payment Method Acquirer for the Payment Method) may deliver or hold any funds or, subject to the terms of our Privacy Policy, any Data as required under such Legal Process, even if you are receiving funds or Data on behalf of other parties. Where permitted by Law, we will make reasonable efforts to provide you Notice of such Legal Process by sending a copy to the email address we have on file for you. Stripe is not responsible for any losses, whether direct or indirect, that you may incur as a result of our response or compliance with a Legal Process.</p>
                    <h1 style={{textAlign: 'left', fontFamily: 'Roboto'}}>Appendix</h1>
                    <h2 style={{textAlign: 'left', fontFamily: 'Roboto'}}>PAYROLL SERVICES AGREEMENT</h2>
                    <p style={{textAlign: 'left'}}>This Services Agreement (“<strong>Services Agreement</strong>”) is a binding legal agreement between and among Customer, Mama's Restauranter, Frontline Work Inc. (“<strong>Frontline</strong>”) and Payroll Company that Frontline chooses as the employer of record (as described below). By using Frontline Payroll Services (“<strong>Frontline Payroll Services</strong>”) provided by the Mama's Restaurant Services Application (“<strong>Application</strong>”), you signify that you have read, understand, accept and agree to be bound by this Services Agreement.</p>
                    <p style={{textAlign: 'left'}}>This Services Agreement includes and incorporates by this reference the agreements and policies (collectively the “<strong>Terms of Service</strong>”) relating to the Application. Frontline reserves the right to revise this Services Agreement and the Terms of Service and all information linked to them from time to time in its sole discretion. Frontline may make such revisions without prior notice: check back often for updates. Unless otherwise provided in such revision, the Services Agreement or Terms of Service, or any revised part of them, will take effect when and as posted.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>EMPLOYMENT RELATIONSHIP AND EMPLOYER OF RECORD</h3>
                    <p style={{textAlign: 'left'}}>Upon accepting a Mama's Restaurant Request or an Open Request that is classified as Payroll with Customer through the Application (each a “<strong>Payrolled Mama's Restaurant Engagement</strong>”), Mama's Restauranter agrees and understands that Frontline will choose the payroll service company (the “<strong>Payroll Company</strong>”) to be the employer of record, meaning the Mama's Restauranter will be an employee of Payroll Company (a “<strong>Payroll Employee</strong>”) solely for Payrolled Mama's Restaurant Engagements. All other Mama's Restaurant Engagements will be on an independent contractor basis, as outlined in the Terms of Service. Frontline will instruct Payroll Company to assign Mama's Restauranter to work for Customer, and Customer is responsible for supervising Mama's Restauranter.</p>
                    <p style={{textAlign: 'left'}}>Except as otherwise stated in this Services Agreement, Payroll Company is responsible for managing payroll, taxes, government documents, benefits (if applicable) and insurance. Customer is responsible for the supervision, direction and control of the day-to-day activities of each Mama's Restauranter assigned to Customer. Mama's Restauranter is responsible for performing the agreed-upon work for Customer.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>HIRING REPRESENTATIONS, DISCLAIMERS AND LIMITATIONS</h3>
                    <p style={{textAlign: 'left'}}>Customer acknowledges and agrees that Customer has selected a Mama's Restauranter to become a Payroll Employee based upon Customer’s determination that the Mama's Restauranter accepted a Mama's Restaurant Request or an Open Request. Neither Frontline nor the Payroll Company makes any representations or warranties as to the skills, experience, background or education of any Mama's Restauranter.</p>
                    <p style={{textAlign: 'left'}}>Mama's Restauranter acknowledges that Mama's Restauranter has agreed to become a Payroll Employee servicing Customer based on Mama's Restauranter’s own determination that Customer offers work acceptable and appropriate for Mama's Restauranter on terms that are acceptable to Mama's Restauranter. Mama's Restauranter agrees to complete such documents as Frontline and/or Payroll Company may legally and reasonably require to complete the employer/employee relationship, including without limitation applicable tax forms and the I-9 requirements of the Immigration and Reform and Control Act of 1986 (collectively, the “<strong>Employment Paperwork</strong>”). Mama's Restauranter understands and agrees that Mama's Restauranter will not become an employee of Payroll Company or be entitled to work for Customer or receive payment from Payroll Company until all Employment Paperwork has been completed and returned to Payroll Company, and Payroll Company has accepted Mama's Restauranter as an employee.</p>
                    <p style={{textAlign: 'left'}}>Customer will continue to issue Open or Mama's Restaurant Requests and pay for Mama's Restauranter through the Application. Frontline assumes no responsibility for and shall exert no control over the projects and work assigned to Mama's Restauranter, nor has Frontline had any role in Customer’s decision to engage Mama's Restauranter via Payroll Services. Frontline shall not direct the work of or supervise (to any degree, directly or indirectly) Mama's Restauranter, nor shall Frontline determine any terms and conditions of Mama's Restauranter’s employment relationship with Payroll Company or Customer (including but not limited to rate of pay, performance evaluation, discipline and/or termination). Frontline merely provides the platform for Customer to request Mama's Restauranter to accept certain work assignments, and separately facilitates the relationship between Customer and the Payroll Company that will handle the administration of payroll and other legal obligations of Customer with regard to Mama's Restauranter. These facts, alone or in combination, do not make Frontline an employer of Mama's Restauranter or a co-employer/joint employer with Customer and/or the Payroll Company. <strong>Mama's Restauranter acknowledges and agrees that he/she is</strong>&nbsp;
                        <strong>not an employee, consultant, or independent contractor of Frontline, and that he/she will not be providing any services to Frontline (directly or indirectly) while employed by Payroll Company</strong>.</p>
                    <p style={{textAlign: 'left'}}>Mama's Restauranter shall be solely responsible for the professional performance of Mama's Restauranter’s work. Mama's Restauranter shall be solely liable for its acts, omissions and negligence.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>PAYROLL SERVICES</h3>
                    <p style={{textAlign: 'left'}}>The following are the services provided by the Payroll Company for Payroll Employees assigned to Customer: (i) calculation and payment of wages (including overtime wages) based upon submitted timesheets; (ii) collection, payment and reporting of all federal, state and local taxes on such wages; (iii) administration and management of unemployment claims; (iv) administration and collection of wages associated with wage garnishments; (v) workers’ compensation coverage. In addition, the Payroll Company shall provide and bear sole responsibility for any health or disability insurance, retirement benefits or other welfare or pension benefits (if any) to which such personnel may be entitled based on eligibility.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>CONTROL OF WORKPLACE</h3>
                    <p style={{textAlign: 'left'}}>Customer and Mama's Restauranter acknowledge and agree that the neither Frontline nor the Payroll Company will control the workplace in which a Payroll Employee will perform services for a Customer.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>PAYROLL EMPLOYEE SUPERVISION AND LIMITATIONS ON SCOPE OF EMPLOYMENT</h3>
                    <p style={{textAlign: 'left'}}>At all times, the Customer will maintain the exclusive supervision, direction and control of the day-to-day activities of each Payroll Employee. The Customer shall be responsible for the implementation and enforcement of any and all workplace laws, rules, regulations and for any procedures that exist for the purpose of preventing the misappropriation, theft or embezzlement of the Customer’s property, including without limitation intellectual property.</p>
                    <p style={{textAlign: 'left'}}>Customer acknowledges and agrees that Payroll Employees are not employees or consultants of Frontline and that Frontline maintains no control over any Mama's Restaurant Engagement, supervision of Mama's Restauranters, payroll practices or other terms and conditions of the working relationship described herein. Customer further acknowledges and agrees that Payroll Employees are employees of the Payroll Company for purposes of payroll processing and, in some cases, the provision of certain statutorily required employee benefits, but that the Payroll Company maintains no control over the work assignments, supervision, or other terms and conditions of the working relationship except as described in this Services Agreement.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>COMPLIANCE WITH LAWS, RULES AND REGULATIONS</h3>
                    <p style={{textAlign: 'left'}}>Customer shall comply with all state, federal and local laws, rules and regulations that govern or relate to its business, workplace, employees (including without limitation Payroll Employees), safety and government contracting. Customer shall comply with all reasonable directives regarding health and safety from the Payroll Company’s workers’ compensation carrier or any government agency. Customer is required to accept and adhere to the Payroll Company’s determination regarding each Payroll Employee’s exempt or non-exempt status for purposes of state and federal overtime laws.</p>
                    <p style={{textAlign: 'left'}}>Mama's Restauranter agrees and understands that Mama's Restauranter shall not work over 8 hours in a day or 29 hours in a week without express written approval by Customer, Frontline, and Payroll Company.</p>
                    <p style={{textAlign: 'left'}}>Notwithstanding the fact that the Payroll Company reserves the right to make determinations regarding the overtime exemption status of each Payroll Employee,&nbsp;
                        <strong>Customer is ultimately and solely responsible for the amount of any wages that are due but unpaid to each of its Payroll Employees</strong>, including without limitation any wages, back wages, and liquidated damages determined to be due and owing in connection with any action challenging the overtime exemption status of any Payroll Employee<strong>.</strong></p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>EQUAL EMPLOYMENT OPPORTUNITY, WORKPLACE LAWS</h3>
                    <p style={{textAlign: 'left'}}>Payroll Company selected by Frontline to provide Payroll Services is an equal opportunity employer and does not discriminate against any candidate, applicant, employee, independent contractor or Payroll Employee on the basis of race, color, religion, sex, national origin, age, creed, ancestry, veteran or military status, disability unrelated to the essential functions of a job, or any other basis prohibited by federal, state or local law. Customer and Payroll Employee shall comply with all federal, state, and local laws that prohibit unlawful discrimination or harassment.</p>
                    <h4 style={{textAlign: 'left'}}><strong>Policy Against Sexual Harassment And Other Illegal Harassment</strong></h4>
                    <p style={{textAlign: 'left'}}>Payroll Company, Customer and Frontline prohibit sexual and other illegal workplace harassment. Customer shall train its Payroll Employees about their rights and responsibilities pursuant to applicable law pertaining to non-harassment or other illegal workplace harassment. Customer will be informed if any special training requirements legally pertain to a Payroll Employee by virtue of that person being employed by Payroll Company. Payroll Company and Customer will provide all Payroll Employees with written information detailing their rights and responsibilities under Customer’s and Payroll Company’s policies against sexual harassment and other illegal workplace harassment. Customer shall inform Payroll Company immediately of any complaint of illegal harassment by or against a Payroll Employee and shall undertake and complete a prompt and thorough investigation of any such complaint. Upon notification, Payroll Company may assist Customer with the investigation of sexual harassment complaints made by or against Payroll Employees, but the costs associated with such investigation shall be borne by Customer.</p>
                    <p style={{textAlign: 'left'}}>If Mama's Restauranter believes that he/she has not been provided equal opportunity in any manner, or if Mama's Restauranter becomes aware of discrimination or harassment, Mama's Restauranter should immediately report that conduct to Frontline at&nbsp;
                        <a href="mailto:support@frontlinework.com">support@frontlinework.com</a>or 302-703-7668.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}><strong>REQUIRED NOTIFICATIONS</strong></h3>
                    <p style={{textAlign: 'left'}}>The Customer will send all written notices and payroll communications to Frontline in accordance with the requirements of the Terms of Service.</p>
                    <p style={{textAlign: 'left'}}>Mama's Restauranter must inform Customer of any work-related injury in connection with services performed for Customer. Customer will provide Frontline with written notice within three (3) days of its own receipt of any notice of a work-related accident or injury, and within three (3) days of its receipt of any notice of any garnishment orders, involuntary deduction orders, notices of IRS liens and other forms of legal process affecting the payment of wages to a Payroll Employee.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>DISCLAIMERS</h3>
                    <p style={{textAlign: 'left'}}>Notwithstanding anything to the contrary, Customer and Mama's Restauranter acknowledge and agree that:</p>
                    <ol style={{textAlign: 'left'}}>
                    <li>&nbsp;Frontline, via the Application, is solely an online venue for buyers and sellers of services and, as such, shall not be responsible for any breach or failure to perform of the Payroll Company or any other action or inaction of the Payroll Company or any Customer or any Mama's Restauranter; and</li>
                    <li>&nbsp;Payroll Company shall not be responsible for any breach or failure to perform of Frontline or any Customer or any other action or inaction of Frontline or any Customer or any Mama's Restauranter.</li>
                    </ol>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>CHANGE OF PAYROLL COMPANY</h3>
                    <p style={{textAlign: 'left'}}>Frontline may designate a new third party payroll company (“<strong>New Company</strong>”), at any time in Frontline’s sole discretion, to perform Frontline Payroll Services. Upon such designation, or at any other time as directed by Frontline, Customer shall: (i) cooperate with such New Company in every reasonable manner to ensure uninterrupted performance of the Frontline Payroll Services; or if directed by Frontline (ii) immediately assume all federal, state and local obligations of an employer to the Payroll Employees and immediately assume full responsibility for providing payroll services and workers’ compensation coverage until such time as a New Company takes over such duties from The Payroll Company. If directed by Frontline, Customer shall inform Payroll Employees that they are no longer covered by the Payroll Company for Frontline Payroll Services, workers’ compensation and/or health care policies.</p>
                    <h3 style={{textAlign: 'left', fontFamily: 'Roboto'}}>GENERAL PROVISIONS</h3>
                    <p style={{textAlign: 'left'}}><strong>Governing Law and Venue</strong>. The Services Agreement and any action related thereto will be governed, controlled, interpreted, and defined by and under the laws of the State as set forth in the Arbitration provision above, without giving effect to any conflicts of laws principles that require the application of the law of a different jurisdiction. Customer and Mama's Restauranter hereby expressly consents to the personal jurisdiction and venue in the state and federal courts or the county in which Customer’s principal place of business is located solely in the event of any lawsuit filed there against Mama's Restauranter by Customer or by Frontline arising from or related to Frontline Payroll Services and/or this Services Agreement.</p>
                    <p style={{textAlign: 'left'}}><strong>Severability</strong>. If any provision of the Services Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of the Services Agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.</p>
                    <p style={{textAlign: 'left'}}><strong>No Assignment</strong>. The Services Agreement, and the party’s rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by either party without the other’s prior written consent, and any attempted Job, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The terms of the Services Agreement will be binding upon assignees. Notwithstanding the foregoing, Customer may, without the consent of Mama's Restauranter, assign any rights and obligations under the Payroll.</p>
                    <p style={{textAlign: 'left'}}><strong>Waiver</strong>. Any waiver or failure to enforce any provision of the Services Agreement on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</p>
                    <p style={{textAlign: 'left'}}><strong>Execution and Delivery; Binding Effect</strong>. The parties will evidence execution and delivery of the Services Agreement with the intention of becoming legally bound, by using Frontline Payroll Services provided by the Application.</p>
                    </span>
                </div>
            </Container>
        </div>
    );
}